import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from networkx.classes import Graph

"""
Catan Board Network Generator (mostly generated by Claude)
==============================

Models a standard Settlers of Catan board as a NetworkX graph, where:
  - **Nodes** (54) are intersection points where settlements can be placed
  - **Edges** (72) are road segments connecting adjacent intersections

Indexing convention
-------------------
Both tiles and nodes are indexed **left-to-right, top-to-bottom** (reading
order), so you can locate any element by scanning the board the way you'd
read a page.

Tiles (19 hexes, rows of 3-4-5-4-3):

           0   1   2
         3   4   5   6
       7   8   9  10  11
        12  13  14  15
          16  17  18

Nodes (54 intersections, rows of 3-4-4-5-5-6-6-5-5-4-4-3):

           0   1   2
          3   4   5   6
          7   8   9  10
        11  12  13  14  15
        16  17  18  19  20
       21  22  23  24  25  26
       27  28  29  30  31  32
        33  34  35  36  37
        38  39  40  41  42
         43  44  45  46
         47  48  49  50
           51  52  53

Each node stores two attributes:
  - 'pos':         (x, y) cartesian coordinates for plotting
  - 'hex_indices': set of tile indices that the node touches (1, 2, or 3 tiles)

Geometry
--------
The board uses **pointy-top** hexagons (vertex at 12 o'clock, flat edges on
left and right), matching the physical Catan game. Hex size defaults to 1.0,
meaning each hex edge has length 1 and the distance between adjacent
intersection nodes is also 1.

Usage
-----
    >>> G, hex_centers = generate_catan_board()
    >>> draw_board(G, hex_centers)                        # plain board
    >>> draw_board(G, hex_centers, tile_data=my_tiles)    # with resources
"""

# ============================================================================
# Board generation
# ============================================================================

def hex_corners(cx, cy, size=1.0):
    """
    Compute the 6 corner positions of a single pointy-top hexagon.

    Corners start at the top (12 o'clock) and proceed clockwise:
      k=0 → top, k=1 → upper-right, k=2 → lower-right,
      k=3 → bottom, k=4 → lower-left, k=5 → upper-left

    Parameters
    ----------
    cx, cy : float — center of the hexagon
    size   : float — distance from center to any vertex (hex "radius")

    Returns
    -------
    list of 6 (x, y) tuples
    """
    return [
        (cx + size * np.cos(np.pi / 2 + np.pi / 3 * k),
         cy + size * np.sin(np.pi / 2 + np.pi / 3 * k))
        for k in range(6)
    ]


def generate_catan_board(size=1.0):
    """
    Build the Catan intersection graph. (Doesn't include resource hexes)

    Algorithm:
      1. Lay out 19 hex centers in a 3-4-5-4-3 grid
      2. Compute all 6 corners per hex (19 × 6 = 114 points)
      3. Deduplicate shared corners → 54 unique nodes
      4. Connect nodes that are exactly one hex-edge apart → 72 edges
      5. Re-number nodes in reading order (left-to-right, top-to-bottom)

    Parameters
    ----------
    size : float — hex edge length / vertex radius (default 1.0)

    Returns
    -------
    G : nx.Graph
        54-node, 72-edge graph.
        Node attributes:
          - 'pos' : (x, y) cartesian coordinates
          - 'hex_indices' : set of tile indices this node touches
    hex_centers : list of (x, y)
        Cartesian centers of the 19 hex tiles, also in reading order.
    """
    # --- Step 1: Hex center positions ---
    # Standard Catan has rows of 3, 4, 5, 4, 3 tiles.
    # For pointy-top hexes the spacing is:
    #   horizontal (within a row) = sqrt(3) * size
    #   vertical (between rows)   = 1.5 * size
    row_counts = [3, 4, 5, 4, 3]    # NOTE: in the future we can extend how different board configurations alter the game outcome
    dx = np.sqrt(3) * size  # horizontal gap between hex centers
    dy = 1.5 * size         # vertical gap between hex rows

    hex_centers = []
    y_top = (len(row_counts) - 1) / 2 * dy  # y-coordinate of the top row
    for row_idx, count in enumerate(row_counts):
        y = y_top - row_idx * dy
        x_start = -(count - 1) / 2 * dx  # center each row horizontally
        for col in range(count):
            hex_centers.append((x_start + col * dx, y))

    # --- Step 2 & 3: Corners → deduplicated nodes ---
    # Adjacent hexes share 2 corners each, so many of the 114 raw corners
    # overlap. We merge any two points closer than `eps` into one node,
    # and track which tiles each node borders.
    eps = 1e-6
    raw_pos = []       # (x, y) for each unique node (before reindexing)
    raw_hex_map = {}   # node_index → {set of tile indices}

    for tile_idx, (cx, cy) in enumerate(hex_centers):
        for corner_idx, (x, y) in enumerate(hex_corners(cx, cy, size)):
            # Check if this corner already exists
            matched = False
            for ni, (ux, uy) in enumerate(raw_pos):
                if abs(x - ux) < eps and abs(y - uy) < eps:
                    raw_hex_map[ni].add(tile_idx)
                    matched = True
                    break
            if not matched:
                ni = len(raw_pos)
                raw_pos.append((x, y))
                raw_hex_map[ni] = {tile_idx}

    # --- Step 4: Find edges ---
    # Two intersection nodes are connected if they are exactly one hex-edge
    # apart (distance = size). This corresponds to being adjacent corners
    # on the same hex.
    raw_edges = []
    for i in range(len(raw_pos)):
        for j in range(i + 1, len(raw_pos)):
            ddx = raw_pos[i][0] - raw_pos[j][0]
            ddy = raw_pos[i][1] - raw_pos[j][1]
            dist = np.sqrt(ddx * ddx + ddy * ddy)
            if abs(dist - size) < eps:
                raw_edges.append((i, j))

    # --- Step 5: Reindex in reading order ---
    # Sort by y descending (top first), then x ascending (left first).
    # Rounding avoids floating-point noise breaking the row grouping.
    sorted_raw = sorted(
        range(len(raw_pos)),
        key=lambda i: (-round(raw_pos[i][1], 3), round(raw_pos[i][0], 3))
    )
    old_to_new = {old: new for new, old in enumerate(sorted_raw)}

    # Build the final graph with clean 0–53 indices (row major indexing)
    G = nx.Graph()
    for new_idx, old_idx in enumerate(sorted_raw):
        x, y = raw_pos[old_idx]
        G.add_node(new_idx, pos=(x, y), hex_indices=raw_hex_map[old_idx])
        # NOTE: extension for the simulation
        G.nodes[new_idx]["owner"] = -1
        G.nodes[new_idx]["turn"] = -1

    for oi, oj in raw_edges:
        G.add_edge(old_to_new[oi], old_to_new[oj])
        # NOTE: extension for the simulation
        G[old_to_new[oi]][old_to_new[oj]]["owner"] = -1
        G[old_to_new[oi]][old_to_new[oj]]["turn"] = -1
        # print(G[old_to_new[oi]][old_to_new[oj]])

    return G, hex_centers

# ============================================================================
# Resource assignment
# ============================================================================

RESOURCES = ['wood', 'wheat', 'sheep', 'brick', 'ore']
PIPS = {2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 8: 5, 9: 4, 10: 3, 11: 2, 12: 1, 0: 0}
# PIPS are derived from the probability of the 2 dice hitting that value, for ex: 6 has the prob of 5/36

def compute_edge_resources(G: Graph, tile_data):
    """
    Assign a resource vector to each edge based on the tiles it borders.

    Each edge in the Catan graph borders 1 tile (coastal) or 2 tiles
    (interior). Both endpoints of an edge touch those same tiles, so the
    edge vector naturally represents the shared resource access along
    that road segment.

    Each of the resource type has a corresponding entry in the edge's
    attribute dicts

    Parameters
    ----------
    G : nx.Graph
        The intersection graph (from generate_catan_board).
    tile_data : list of (resource, number) tuples, length 19
        e.g. [('wood', 8), ('brick', 10), ..., ('desert', 0)]

    Returns
    -------
    G : the same graph, with new edge attributes:
        - '[resource]' : resource name -> pip count (all 5 resources initialized to 0)
        - 'total_pips'   : int, sum of all pips on this edge
    """
    for u, v in G.edges():
        # Initialize all resources to 0 so every edge has a consistent set of keys
        for res in RESOURCES:
            G[u][v][res] = 0
        total_pips = 0
        shared_tiles = G.nodes[u]['hex_indices'] & G.nodes[v]['hex_indices']
        for tile_idx in shared_tiles:
            resource, number = tile_data[tile_idx]
            if resource != 'desert':
                G[u][v][resource] += PIPS[number]
                total_pips += PIPS[number]

        G[u][v]['total_pips'] = total_pips

    return G


BEGINNER_TILES = [
    ('ore', 10), ('sheep', 2), ('wood', 9),                              # row 0
    ('wheat', 12), ('brick', 6), ('sheep', 4), ('brick', 10),            # row 1
    ('wheat', 9), ('wood', 11), ('desert', 0), ('wood', 3), ('ore', 8),  # row 2
    ('wood', 8), ('ore', 3), ('wheat', 4), ('sheep', 5),                 # row 3
    ('brick', 5), ('wheat', 6), ('sheep', 11),                           # row 4
]

def generate_beginner_board_graph():
    G, hex_centers = generate_catan_board()
    G = compute_edge_resources(G, BEGINNER_TILES)
    return G, hex_centers, BEGINNER_TILES

def generate_random_resource_tiles():
    return None

# TODO!!!
def generate_random_board_graph():
    G, hex_centers = generate_catan_board()
    # TODO add random resource tile generator
    random_tiles = generate_random_resource_tiles()
    G = compute_edge_resources(G, random_tiles)
    return G, hex_centers, random_tiles

# TODO: consider memoizing this for performance improvements
def is_node_settleable(network: Graph, node_idx: int) -> bool:
    """
        returns if the node_idx settlement can be settled according to the rulebook
    """
    # check if the settlement itself is empty
    if network.nodes[node_idx]["owner"] != -1:
        return False
    # check the 1 road away rule
    if any([network.nodes[neigh_idx]["owner"] != -1 for neigh_idx in network.neighbors(node_idx)]):
        return False
    return True

def is_edge_roadable_draft(network: Graph, edge: tuple[int, int], id: int, turn: int) -> bool:
    """
        returns if an edge is valid for placing a road according to the rulebook
    """

    if network.edges[edge]["owner"] != -1:
        return False

    # check if the edge can be placed according to the rulebook
    # NOTE: breaks short-circuiting
    is_owner_0 = network.nodes[edge[0]]["owner"] == id
    is_turn_0 = network.nodes[edge[0]]["turn"] == turn
    is_owner_1 = network.nodes[edge[1]]["owner"] == id
    is_turn_1 = network.nodes[edge[0]]["turn"] == turn

    if (not is_owner_0 or not is_turn_0) and (not is_owner_1 or not is_turn_1):
        return False

    return True


